### ISSUE TITLE
Small issues with CRG 4 data files

### ISSUE THREAD

**Issue by frank-weinberg** [AdamSmasherDerby/CRG-To-Statsbook#5]
- In a SP line in the SK sheet, the tool will write a 0 in the NI column. (Aside frmo breaking score calculation, if there are points in that line, these will also cause an exception in the statsbook tool upon parsing the file.)
- The tool treats the FO/EXP penalty (`Penalty(0)` in the data) as a regular penalty.
- n/a and ? on the LT sheet are not converted into the corresponding comments

**Comment by AdamSmasherDerby** [comment]
See, and this is why we need an API. :)  I'll get on this.

**Comment by AdamSmasherDerby** [comment]
Closed by 68eba5e40287f37d3fe95aab8f8629a041fc49df and b96fe77c17ac047ed24954dd77eecfb710197c71

The XLSX-populate library does not support writing comments, so for the time being ?? and n/a will be written directly to the statsbook.  If the library adds commenting in the future, this has been done in a way that will facilitate quickly converting these to comments.
