### ISSUE TITLE
Game Data created on a Mac with CRGv4 ist creating errors 

### ISSUE THREAD

**Issue by reflexdd** [AdamSmasherDerby/CRG-To-Statsbook#6]
I did run crg-scoreboard_v4.0.0 on a Mac last weekend and tried to convert the game Data to excel.
That works at first sight and all the Data seems to be filled correctly but testing it with the StatsBook Tool throws a ton of unexpected errors and warnings like  "Lead box checked more than once in a single jam" for every Jam. I tried to convert it on a Mac and on a PC with the newest versions and with fresh Statsbook-Files.

[191207-Game2.zip](https://github.com/AdamSmasherDerby/CRG-To-Statsbook/files/3939394/191207-Game2.zip)

**Comment by reflexdd** [comment]
It seems that the same beaviour is also happening on Game-Data created on a PC.
Empty Boxes on Lineup and Score sheets seem to have an unvisible value wich leads to those errors

**Comment by AdamSmasherDerby** [comment]
Thanks for the report - I'll have a look!

**Comment by AdamSmasherDerby** [comment]
Reflexdd - are you CERTAIN that's the .json file you used to generate those statsbooks?  When I run the same JSON file through the converter on my computer, I get a statsbook file out that LOOKS the same as yours, but is 100+ kilobytes smaller, and breaks the statsbook checker even worse than yours does.

**Comment by AdamSmasherDerby** [comment]
Hang on - I figured that part out.  If you export the data from the scoreboard, and then try to error check it without ever opening the sheet in Excel, it doesn't work, because Excel has to run all the formulas.   OK, on to the next bit...

**Comment by AdamSmasherDerby** [comment]
OK - looks like most of this is actually issues with the Statsbook Checker, rather than the exporter.  Because all of the libraries for dealing with Excel are so poorly documented, I'm constantly finding new and exciting ways to break the Excel file format.  I'll compile and upload some fixes later tonight to both programs.

**Comment by AdamSmasherDerby** [comment]
Closed by 49473dc4da14ae51c79c3d8931d47c36a2110675
